#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: $0 [--suffix SUFFIX] [--margin MARGIN]
  --suffix   set the suffix value
  --margin   set the margin value
  -h|--help  show this help
EOF
  exit 1
}

suffix=""
margin="0.25in"
font="Roboto Light"
fontsize="9pt"  # <--- Defined here as lowercase

# parse args
while (("$#")); do
  case "$1" in
  --suffix)
    [[ -n $2 ]] || usage
    suffix="-$2"
    shift 2
    ;;
  --margin)
    [[ -n $2 ]] || usage
    margin=$2
    shift 2
    ;;
  -h | --help)
    usage
    ;;
  *)
    echo "Error: unknown option '$1'" >&2
    usage
    ;;
  esac
done

if [ -f "Resume-Jesse-Earle.pdf" ]; then
  echo "Resume PDF exists"
fi

resume_name="Resume-Jesse-Earle$suffix"
resume_tex_md="$resume_name.tex.md"
resume_html="$resume_name.html"
resume_pdf="$resume_name.pdf"
resume_docx="$resume_name.docx"

echo "generating $resume_html from $resume_tex_md"
echo "generating $resume_pdf from $resume_tex_md"
echo "with margin $margin"
echo "with fontsize $fontsize"

# HTML
pandoc -o "$resume_html" "$resume_tex_md"

# PDF
pandoc -o "$resume_pdf" "$resume_tex_md" \
  --pdf-engine=xelatex \
  -H preamble.tex \
  -V documentclass=extarticle \
  -V geometry:margin=$margin \
  -V mainfont="$font" \
  -V mainfontoptions="BoldFont=Roboto Condensed Medium" \
  -V fontsize=$fontsize \
  -V colorlinks=true \
  -V urlcolor=blue

# Docx
pandoc -o "$resume_docx" "$resume_tex_md" \
  -H preamble.tex \
  -V geometry:margin=$margin \
  -V fontsize=$fontsize \
  -V documentclass=extarticle